on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: |
          if [ "${{ github.event_name }}" = "release" ]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
          fi

      - name: Update package.json version
        run: |
          # Remove 'v' prefix if present
          CLEAN_VERSION=$(echo $VERSION | sed 's/^v//')
          # Update package.json version
          npm version $CLEAN_VERSION --no-git-tag-version --allow-same-version

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: 'chore: update package.json version to ${{ env.VERSION }}'
          title: 'Update package.json version to ${{ env.VERSION }}'
          body: |
            Updates package.json version to match the latest release tag.

            - Version: ${{ env.VERSION }}
            - Auto-generated by version workflow
          branch: 'chore/update-version'
          base: 'main'
          delete-branch: true
